<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup />

  <ItemGroup Condition="Exists('secrets.json')">
    <Content Remove="secrets.json" />
    <None Include="secrets.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.50" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ananke.Orchestration\Ananke.Orchestration.csproj" />
    <ProjectReference Include="..\..\Ananke.Orchestration.OpenAI\Ananke.Orchestration.OpenAI.csproj" />
    <ProjectReference Include="..\..\Ananke.OpenTelemetry\Ananke.OpenTelemetry.csproj" />
  </ItemGroup>

</Project>
