<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ananke.Roles\Ananke.Roles.csproj" />
    <ProjectReference Include="..\..\Ananke.Platforms.Slack\Ananke.Platforms.Slack.csproj" />
    <ProjectReference Include="..\Ananke.TestHelpers\Ananke.TestHelpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
