namespace Ananke.Organics.Division;

/// <summary>
/// A proposed division: which children to create and which tools each gets.
/// Generated by <see cref="IDivisionPolicy"/> and executed by
/// <see cref="IWorkflowDivider"/>.
/// </summary>
public sealed record DivisionPlan
{
    /// <summary>Name of the cell that should divide.</summary>
    public required string ParentWorkflow { get; init; }

    /// <summary>Specifications for each child cell to create.</summary>
    public required IReadOnlyList<ChildSpec> Children { get; init; }

    /// <summary>Human-readable reason for this division.</summary>
    public required string Reason { get; init; }

    /// <summary>
    /// Empirical entry IDs that influenced this decision. Used for reward
    /// propagation — if the division outcome is positive, these entries are
    /// reinforced; if negative, they are contradicted.
    /// </summary>
    public IReadOnlyList<string> InfluencingEntries { get; init; } = [];
}

/// <summary>Specification for a child cell to be created during division.</summary>
public sealed record ChildSpec
{
    /// <summary>Name for the new child cell.</summary>
    public required string Name { get; init; }

    /// <summary>Primary domain this child will serve.</summary>
    public required string Domain { get; init; }

    /// <summary>Tool names assigned to this child.</summary>
    public required IReadOnlyList<string> Tools { get; init; }

    /// <summary>Job names assigned to this child.</summary>
    public required IReadOnlyList<string> Jobs { get; init; }

    /// <summary>Optional system prompt override for this child's agent jobs.</summary>
    public string? SystemPromptOverride { get; init; }

    /// <summary>
    /// Optional target platform for this child (e.g. <c>"azure-ai"</c>, <c>"vertex-ai"</c>).
    /// When <see langword="null"/>, the child runs on the local host.
    /// Set by <c>FederatedDivisionPolicy</c> when profile-aware placement is active.
    /// </summary>
    public string? TargetPlatform { get; init; }
}
