// ChildSpec was moved to Ananke.Abstractions.Agents.ChildSpec (global alias in GlobalAliases.cs).
namespace Ananke.Organics.Division;

/// <summary>
/// A proposed division: which children to create and which tools each gets.
/// Generated by <see cref="IDivisionPolicy"/> and executed by
/// <see cref="IWorkflowDivider"/>.
/// </summary>
public sealed record DivisionPlan
{
    /// <summary>Name of the cell that should divide.</summary>
    public required string ParentWorkflow { get; init; }

    /// <summary>Specifications for each child cell to create.</summary>
    public required IReadOnlyList<ChildSpec> Children { get; init; }

    /// <summary>Human-readable reason for this division.</summary>
    public required string Reason { get; init; }

    /// <summary>
    /// Empirical entry IDs that influenced this decision. Used for reward
    /// propagation — if the division outcome is positive, these entries are
    /// reinforced; if negative, they are contradicted.
    /// </summary>
    public IReadOnlyList<string> InfluencingEntries { get; init; } = [];
}

