<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Ananke.A2A\Ananke.A2A.csproj" />
    <ProjectReference Include="..\..\..\Ananke.Orchestration\Ananke.Orchestration.csproj" />
  </ItemGroup>

</Project>
